package foo.jdbc;

// java.sql.ResultSet
// A table of data representing a database result set, 
// which is usually generated by executing a statement that queries the database. 

public class ResultSetFoo {

}
